version: "3.2"
services:
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A uploader worker --loglevel=INFO --concurrency=30
    depends_on:
      - redis
    volumes:
      - .:/tasker
